name: Run the tests

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        label:
          - osx-64
          - win-64
          - linux-64
        prefix:
          - /Users/runner/miniconda3/envs/bioptim
          - C:\Miniconda3\envs\bioptim
          - /usr/share/miniconda3/envs/bioptim
        shard: [1, 2, 3, 4]  # added shards
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: bioptim
          environment-file: environment.yml

      - name: Print mamba info
        run: | 
          mamba config --show
          mamba info
          mamba list

      - name: Install extra dependencies
        run: mamba install pytest-cov black pytest pytest-cov codecov packaging -cconda-forge

      - name: Install ACADOS on Linux
        run: |
          cd external
          ./acados_install_linux.sh
          cd ..
        if: matrix.label == 'linux-64'

      - name: Install ACADOS on Mac
        run: |
          cd external
          ./acados_install_mac.sh
          cd ..
        if: matrix.label == 'osx-64'

      - name: Run the actual tests
        run: pytest -v --color=yes --cov-report term-missing --cov=bioptim tests/shard${{ matrix.shard }}  # modified to select shard
          
      - name: Test installed version of bioptim
        run: | 
          python setup.py install
          cd
          python -c "import bioptim"
        
      - name: Upload coverage to Codecov
        run: codecov
        if: matrix.label == 'linux-64'
